require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GradesStudentsController do

  # This should return the minimal set of attributes required to create a valid
  # GradesStudent. As you add validations to GradesStudent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GradesStudentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all grades_students as @grades_students" do
      grades_student = GradesStudent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:grades_students).should eq([grades_student])
    end
  end

  describe "GET show" do
    it "assigns the requested grades_student as @grades_student" do
      grades_student = GradesStudent.create! valid_attributes
      get :show, {:id => grades_student.to_param}, valid_session
      assigns(:grades_student).should eq(grades_student)
    end
  end

  describe "GET new" do
    it "assigns a new grades_student as @grades_student" do
      get :new, {}, valid_session
      assigns(:grades_student).should be_a_new(GradesStudent)
    end
  end

  describe "GET edit" do
    it "assigns the requested grades_student as @grades_student" do
      grades_student = GradesStudent.create! valid_attributes
      get :edit, {:id => grades_student.to_param}, valid_session
      assigns(:grades_student).should eq(grades_student)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GradesStudent" do
        expect {
          post :create, {:grades_student => valid_attributes}, valid_session
        }.to change(GradesStudent, :count).by(1)
      end

      it "assigns a newly created grades_student as @grades_student" do
        post :create, {:grades_student => valid_attributes}, valid_session
        assigns(:grades_student).should be_a(GradesStudent)
        assigns(:grades_student).should be_persisted
      end

      it "redirects to the created grades_student" do
        post :create, {:grades_student => valid_attributes}, valid_session
        response.should redirect_to(GradesStudent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grades_student as @grades_student" do
        # Trigger the behavior that occurs when invalid params are submitted
        GradesStudent.any_instance.stub(:save).and_return(false)
        post :create, {:grades_student => {  }}, valid_session
        assigns(:grades_student).should be_a_new(GradesStudent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GradesStudent.any_instance.stub(:save).and_return(false)
        post :create, {:grades_student => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested grades_student" do
        grades_student = GradesStudent.create! valid_attributes
        # Assuming there are no other grades_students in the database, this
        # specifies that the GradesStudent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GradesStudent.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => grades_student.to_param, :grades_student => { "these" => "params" }}, valid_session
      end

      it "assigns the requested grades_student as @grades_student" do
        grades_student = GradesStudent.create! valid_attributes
        put :update, {:id => grades_student.to_param, :grades_student => valid_attributes}, valid_session
        assigns(:grades_student).should eq(grades_student)
      end

      it "redirects to the grades_student" do
        grades_student = GradesStudent.create! valid_attributes
        put :update, {:id => grades_student.to_param, :grades_student => valid_attributes}, valid_session
        response.should redirect_to(grades_student)
      end
    end

    describe "with invalid params" do
      it "assigns the grades_student as @grades_student" do
        grades_student = GradesStudent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GradesStudent.any_instance.stub(:save).and_return(false)
        put :update, {:id => grades_student.to_param, :grades_student => {  }}, valid_session
        assigns(:grades_student).should eq(grades_student)
      end

      it "re-renders the 'edit' template" do
        grades_student = GradesStudent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GradesStudent.any_instance.stub(:save).and_return(false)
        put :update, {:id => grades_student.to_param, :grades_student => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grades_student" do
      grades_student = GradesStudent.create! valid_attributes
      expect {
        delete :destroy, {:id => grades_student.to_param}, valid_session
      }.to change(GradesStudent, :count).by(-1)
    end

    it "redirects to the grades_students list" do
      grades_student = GradesStudent.create! valid_attributes
      delete :destroy, {:id => grades_student.to_param}, valid_session
      response.should redirect_to(grades_students_url)
    end
  end

end
